backoffice:
    resource: "@BackofficeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

user_bundle:
   resource: "@BackofficeBundle/Resources/config/routing.yml"